FROM docker.io/rust:1.95-slim as builder
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release


FROM docker.io/debian:bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y iproute2

COPY --from=builder /app/target/release/server ./server

EXPOSE 3000

CMD ["./server"]
